// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl6OwaUWHcZn1wc2fdVZByxBOVW693cUo',
    appId: '1:12072642562:web:1aa711c4cbc5e952041f1b',
    messagingSenderId: '12072642562',
    projectId: 'flutterapp-7efbd',
    authDomain: 'flutterapp-7efbd.firebaseapp.com',
    storageBucket: 'flutterapp-7efbd.firebasestorage.app',
    measurementId: 'G-G73P2N9QM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFSk0uq64qzDcvexa9zExdhJAsvkQtpiQ',
    appId: '1:12072642562:android:c46b1c8afa234fb5041f1b',
    messagingSenderId: '12072642562',
    projectId: 'flutterapp-7efbd',
    storageBucket: 'flutterapp-7efbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEvqHKwLUdM_wucca3d1dSOWCaZletlzg',
    appId: '1:12072642562:ios:e0b95b462d7089fa041f1b',
    messagingSenderId: '12072642562',
    projectId: 'flutterapp-7efbd',
    storageBucket: 'flutterapp-7efbd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEvqHKwLUdM_wucca3d1dSOWCaZletlzg',
    appId: '1:12072642562:ios:e0b95b462d7089fa041f1b',
    messagingSenderId: '12072642562',
    projectId: 'flutterapp-7efbd',
    storageBucket: 'flutterapp-7efbd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl6OwaUWHcZn1wc2fdVZByxBOVW693cUo',
    appId: '1:12072642562:web:532d6d7cc8fc0734041f1b',
    messagingSenderId: '12072642562',
    projectId: 'flutterapp-7efbd',
    authDomain: 'flutterapp-7efbd.firebaseapp.com',
    storageBucket: 'flutterapp-7efbd.firebasestorage.app',
    measurementId: 'G-MW5Z4ZM0NS',
  );
}
